import { Icon } from '@/components/ui/icon'

export const NOTIFICATION_TYPES = {
  CYCLE: "cycle",
  DELIVERY: "delivery",
  OTP: "otp",
  MEDICATION: "medication",
  SLEEP: "sleep",
  STEPS: "steps",
  DOCUMENT: "document",
  APPROVAL: "approval",
} as const

export const INITIAL_NOTIFICATIONS = [
  {
    id: 1,
    title: "Upcoming Cycle 3",
    message: "Your 3rd treatment cycle is scheduled for January 15, 2025",
    type: NOTIFICATION_TYPES.CYCLE,
    isRead: false,
    timestamp: "2 hours ago",
    icon: (props: any) => <Icon name="calendar" {...props} />,
    color: "text-purple-600",
    bgColor: "bg-purple-50",
  },
  {
    id: 2,
    title: "Delivery Update",
    message: "Your medication package has been shipped and will arrive tomorrow",
    type: NOTIFICATION_TYPES.DELIVERY,
    isRead: false,
    timestamp: "4 hours ago",
    icon: (props: any) => <Icon name="localShipping" {...props} />,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
  },
  {
    id: 3,
    title: "Delivery OTP",
    message: "Your delivery OTP is 4567. Please share with delivery person.",
    type: NOTIFICATION_TYPES.OTP,
    isRead: true,
    timestamp: "1 day ago",
    icon: (props: any) => <Icon name="alertCircle" {...props} />,
    color: "text-orange-600",
    bgColor: "bg-orange-50",
  },
  {
    id: 4,
    title: "Medication Reminder",
    message: "Don't forget to take your evening medication",
    type: NOTIFICATION_TYPES.MEDICATION,
    isRead: false,
    timestamp: "6 hours ago",
    icon: (props: any) => <Icon name="medication" {...props} />,
    color: "text-green-600",
    bgColor: "bg-green-50",
  },
  {
    id: 5,
    title: "Sleep Log Reminder",
    message: "Please log your sleep hours for yesterday",
    type: NOTIFICATION_TYPES.SLEEP,
    isRead: true,
    timestamp: "1 day ago",
    icon: (props: any) => <Icon name="bedtime" {...props} />,
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
  },
  {
    id: 6,
    title: "Steps Goal Achieved",
    message: "Congratulations! You've reached your daily steps goal of 10,000",
    type: NOTIFICATION_TYPES.STEPS,
    isRead: true,
    timestamp: "2 days ago",
    icon: (props: any) => <Icon name="footprints" {...props} />,
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
  },
  {
    id: 7,
    title: "Document Upload Required",
    message: "Please upload your discharge summary to start the next cycle",
    type: NOTIFICATION_TYPES.DOCUMENT,
    isRead: false,
    timestamp: "3 days ago",
    icon: (props: any) => <Icon name="fileText" {...props} />,
    color: "text-red-600",
    bgColor: "bg-red-50",
  },
  {
    id: 8,
    title: "Document Approved",
    message: "Your lab report has been reviewed and approved",
    type: NOTIFICATION_TYPES.APPROVAL,
    isRead: true,
    timestamp: "4 days ago",
    icon: (props: any) => <Icon name="checkCircle" {...props} />,
    color: "text-green-600",
    bgColor: "bg-green-50",
  },
]
